{{- $labelChart := include "prometheus-pushgateway.chart" $ -}}
{{- $labelApp := include "prometheus-pushgateway.name" $ -}}
{{- $labels := dict "app" $labelApp "chart" $labelChart "release" .Release.Name "heritage" .Release.Service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-pushgateway.fullname" . }}
  labels:
{{ merge .Values.serviceLabels $labels | toYaml | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "prometheus-pushgateway.name" . }}
    release: {{ .Release.Name }}
